---
- name: "Add the Broad Sentinelone yum repository."
  yum_repository:
    name: 3rdparty-dsp
    baseurl: "{{ repo }}-$basearch"
    description: "Broad Institute Third Party Packages - DSP - CentOS $releasever - $basearch"
    gpgcheck: no
    enabled: yes
    repo_gpgcheck: no
